# radis run with this command docker-compose up
services:
  skinet:
    image: docker.io.library/skinet
    depends_on:
      - db
    container_name: demoapp
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: dockerfile  
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD : secret
      POSTGRES_USER : appuser
      POSTGRES_DB : skinet
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data    
volumes:
  redis-data:
  postgres-data : 